version = 1

exclude_patterns = [
  "examples/**",
]

[[analyzers]]
name = "python"
enabled = true
max_line_length = 100
skip_doc_coverage = ["module"]

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"
enabled = true