name: Runs tests
on:
  pull_request:
  push:
  schedule:
    - cron:  "0 0 * * *"
    
jobs:
  build:
    platform: ubuntu-latest
    build:
      strategy:
        matrix:
          python-version: "3.8"
          include:
            - tox_env: py38
              python_version: "3.8"
              friendly_name: Python 3.8 - Test
            - tox_env: py39
              python_version: "3.9"
              friendly_name: Python 3.9 - Test
            - tox_env: py310
              python_version: "3.10"
              friendly_name: Python 3.10 - Test
           fail-fast: false
           
      name: ${{ matrix.friendly_name }}
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
            
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install tox
          
        - name: Test with tox
          run: tox
          env:
            TOXENV: ${{ matrix.tox_env }}
